In [3]:
import numpy as np

In [5]:
my_list=[1,2,3,4]
my_list

[1, 2, 3, 4]

In [7]:
array=np.array(my_list,dtype=int)
array

array([1, 2, 3, 4])

In [9]:
print(type(array)) #Describes the type
print(len(array)) #Count the elements
print(array.ndim) #GIves the dimension
print(array.shape) #describes the shape

<class 'numpy.ndarray'>
4
1
(4,)


In [15]:
rearray=array.reshape(2,2) #Used to reshape the desired array
print(rearray)
rearray.shape

[[1 2]
 [3 4]]


(2, 2)

In [19]:
list=[1,2,3,4,5]
list1=[4,4,6,7,8]
list2=[6,7,8,9,0]
com_array=np.array([list,list1,list2])
print(com_array)

[[1 2 3 4 5]
 [4 4 6 7 8]
 [6 7 8 9 0]]


In [21]:
com_array.shape

(3, 5)

In [23]:
com_array.reshape(1,15)

array([[1, 2, 3, 4, 5, 4, 4, 6, 7, 8, 6, 7, 8, 9, 0]])

In [25]:
a=np.array([1,2,3],dtype=int)
b=np.array([3,4,5],dtype=int)

In [27]:
print(a)
print(b)

[1 2 3]
[3 4 5]


In [31]:
Sum=np.add(a,b)
print(Sum)

[4 6 8]


In [37]:
Diff=np.subtract(a,b)
print(Diff)

[-2 -2 -2]


In [39]:
Diff=np.subtract(b,a)
print(Diff)

[2 2 2]


In [45]:
Mul=np.multiply(a,b)
print(Mul)
Quotient=np.divide(a,b)
print(Quotient)
Dot=np.dot(a,b)
print(Dot)

[ 3  8 15]
[0.33333333 0.5        0.6       ]
26
